//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.17929
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SiegeOnlineDataViewer.Properties {
    using System;
    
    
    /// <summary>
    ///   Класс ресурса со строгой типизацией для поиска локализованных строк и т.д.
    /// </summary>
    // Этот класс создан автоматически классом StronglyTypedResourceBuilder
    // с помощью такого средства, как ResGen или Visual Studio.
    // Чтобы добавить или удалить член, измените файл .ResX и снова запустите ResGen
    // с параметром /str или перестройте свой проект VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Возвращает кэшированный экземпляр ResourceManager, использованный этим классом.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SiegeOnlineDataViewer.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Перезаписывает свойство CurrentUICulture текущего потока для всех
        ///   обращений к ресурсу с помощью этого класса ресурса со строгой типизацией.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на vdg1981@mail.ru.
        /// </summary>
        internal static string Email {
            get {
                return ResourceManager.GetString("Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap LogoGame {
            get {
                object obj = ResourceManager.GetObject("LogoGame", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Map_Point_Small {
            get {
                object obj = ResourceManager.GetObject("Map_Point_Small", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Icon, аналогичного (Значок).
        /// </summary>
        internal static System.Drawing.Icon ProgramIcon {
            get {
                object obj = ResourceManager.GetObject("ProgramIcon", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на ServerCityBotsDuelNpc=BotsDuel
        ///ServerCityRandomDuelNpc=RandomDuelNpc
        ///ServerPrisonerAmazonNpc=PrisonerAmazonNpc
        ///ServerNpcGangster_Plague=NpcGangster_Plague
        ///ServerTournamentTicketNPC=TournamentTicketNPC
        ///ServerSnowManQuestNpc=ServerSnowManQuestNpc
        ///ServerMorozovecShopNpc=MorozovecShopNpc
        ///ServerGangster_Peasant_Snowball_A=NPC_Peasant_Snowball_A
        ///ServerGangster_Archer_Snowball_A=NPC_Archer_Snowball_A
        ///ServerGangster_Ballista_Snowball_A=NPC_Ballista_Snowball_A
        ///ServerGangster_Big_Snowball=NPC_Big_Snowball
        /// [остаток строки не уместился]&quot;;.
        /// </summary>
        internal static string ServerCodes {
            get {
                return ResourceManager.GetString("ServerCodes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на GuardGateNpc_1 = Стражник
        ///GuardGateNpc_3 = Стражник Восточных ворот
        ///GuardGateNpc_4 = Стражник Восточных ворот
        ///ArmourerRuggyNpc = Оружейник Ругги
        ///HealerNpc = Целитель Саббах
        ///AssistantArchitectNpc = Помощник архитектора
        ///AssistantToTheQuartermaster_RightNpc = Помощник интенданта
        ///AssistantToTheQuartermaster_LeftNpc = Помощник интенданта
        ///QuestFrontierGuardNpc = Страж границы
        ///ServerAlchemist = Алхимик Малх
        ///QuestNpcIronOre_1 = Айронгрофт
        ///HohotosQuestNpc = Весёлый Хохотос
        ///LeaderFreedOrderLandNpc = Предв [остаток строки не уместился]&quot;;.
        /// </summary>
        internal static string ServerNPC {
            get {
                return ResourceManager.GetString("ServerNPC", resourceCulture);
            }
        }
    }
}
